spring:
  application:
    name: mock-service-service
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

